<?
  require('includes/boxes/configuration.php');
  require('includes/boxes/modules.php');
  require('includes/boxes/catalog.php');
  require('includes/boxes/customers.php');
  require('includes/boxes/taxes.php');
  require('includes/boxes/banners.php');
  require('includes/boxes/localization.php');
  require('includes/boxes/statistics.php');
  require('includes/boxes/tools.php');
  require('includes/boxes/mail.php');
?>
